name: pachalik_registry
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: 
  flutter_riverpod: 
  shared_preferences: 
  google_fonts: 
  flutter_hooks: 
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  intl: ^0.19.0
dev_dependencies:
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  fl_chart:
  share_plus:
  

flutter:
  uses-material-design: true
  generate: true

  # Add this section for localization
  assets:
    - assets/