name: pachalik_registry
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: 
  flutter_riverpod: 
  shared_preferences: 
  google_fonts: 
  flutter_hooks: 
  sqflite_common_ffi:
  path_provider: 
  intl: ^0.19.0
  fl_chart:
  share_plus:
  sqflite: 
  path: 

dev_dependencies:
  build_runner: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  

flutter:
  uses-material-design: true
  generate: true

  # Add this section for localization
  assets:
    - assets/