final List<Map<String, dynamic>> dummyData = [
  {
    'cnie': 'L36567',
    'first_name_ar': 'محمد',
    'first_name_en': 'Mohammed',
    'last_name_ar': 'العلوي',
    'last_name_en': 'Alaoui',
    'gender_ar': 'ذكر',
    'gender_en': 'Male',
    'marital_status_ar': 'متزوج',
    'marital_status_en': 'Married',
    'father_name_ar': 'عبد الله',
    'father_name_en': 'Abdullah',
    'father_cnie': 'L123456',
    'mother_cnie': 'L123457',
    'mother_name_ar': 'فاطمة الزهراء',
    'mother_name_en': 'Fatima Zahra',
    'grandfather_paternal_ar': 'أحمد',
    'grandfather_paternal_en': 'Ahmed',
    'grandfather_maternal_ar': 'إدريس',
    'grandfather_maternal_en': 'Idriss',
    'grandmother_paternal_ar': 'عائشة',
    'grandmother_paternal_en': 'Aicha',
    'grandmother_maternal_ar': 'حليمة',
    'grandmother_maternal_en': 'Halima',
    'birth_date': '1990-05-15',
    'birth_location_ar': 'الدار البيضاء',
    'birth_location_en': 'Casablanca',
    'address_ar': 'حي السلام، زنقة 5، رقم 23',
    'address_en': 'Hay Salam, Street 5, No 23',
    'voter_circle': '13',
    'voter_number': '6709',
    'idcs': '9876543210',
    'civil_registry_number': '123/1990',
    'political_affiliation_ar': 'مستقل',
    'political_affiliation_en': 'Independent',
    'job_ar': 'مهندس',
    'job_en': 'Engineer',
    'nationality_ar': 'مغربي',
    'nationality_en': 'Moroccan',
    'second_nationality_ar': 'فرنسي',
    'second_nationality_en': 'French'
  },
  {
    'cnie': 'L843567',
    'first_name_ar': 'أحمد',
    'first_name_en': 'Ahmed',
    'last_name_ar': 'الفاسي',
    'last_name_en': 'Fassi',
    'gender_ar': 'ذكر',
    'gender_en': 'Male',
    'marital_status_ar': 'أعزب',
    'marital_status_en': 'Single',
    'father_name_ar': 'محمد',
    'father_name_en': 'Mohammed',
    'father_cnie': 'L123458',
    'mother_cnie': 'L123459',
    'mother_name_ar': 'مريم',
    'mother_name_en': 'Maryam',
    'grandfather_paternal_ar': 'حسن',
    'grandfather_paternal_en': 'Hassan',
    'grandfather_maternal_ar': 'علي',
    'grandfather_maternal_en': 'Ali',
    'grandmother_paternal_ar': 'خديجة',
    'grandmother_paternal_en': 'Khadija',
    'grandmother_maternal_ar': 'زينب',
    'grandmother_maternal_en': 'Zineb',
    'birth_date': '1985-08-20',
    'birth_location_ar': 'فاس',
    'birth_location_en': 'Fes',
    'address_ar': 'حي النصر، زنقة 10، رقم 45',
    'address_en': 'Hay Nasr, Street 10, No 45',
    'voter_circle': '2',
    'voter_number': '413',
    'idcs': '9876543211',
    'civil_registry_number': '456/1985',
    'political_affiliation_ar': 'حزب العدالة والتنمية',
    'political_affiliation_en': 'Justice and Development Party',
    'job_ar': 'طبيب',
    'job_en': 'Doctor',
    'nationality_ar': 'مغربي',
    'nationality_en': 'Moroccan',
    'second_nationality_ar': null,
    'second_nationality_en': null
  },
  {
    'cnie': 'L154365',
    'first_name_ar': 'فاطمة',
    'first_name_en': 'Fatima',
    'last_name_ar': 'الرباطي',
    'last_name_en': 'Rbati',
    'gender_ar': 'أنثى',
    'gender_en': 'Female',
    'marital_status_ar': 'متزوجة',
    'marital_status_en': 'Married',
    'father_name_ar': 'كريم',
    'father_name_en': 'Karim',
    'father_cnie': 'L123460',
    'mother_cnie': 'L123461',
    'mother_name_ar': 'خديجة',
    'mother_name_en': 'Khadija',
    'grandfather_paternal_ar': 'يوسف',
    'grandfather_paternal_en': 'Youssef',
    'grandfather_maternal_ar': 'عمر',
    'grandfather_maternal_en': 'Omar',
    'grandmother_paternal_ar': 'سعيدة',
    'grandmother_paternal_en': 'Saida',
    'grandmother_maternal_ar': 'نعيمة',
    'grandmother_maternal_en': 'Naima',
    'birth_date': '1995-03-10',
    'birth_location_ar': 'الرباط',
    'birth_location_en': 'Rabat',
    'address_ar': 'حي الرياض، زنقة 15، رقم 67',
    'address_en': 'Hay Riad, Street 15, No 67',
    'voter_circle': '6',
    'voter_number': '88',
    'idcs': '9876543212',
    'civil_registry_number': '789/1995',
    'political_affiliation_ar': 'حزب الاستقلال',
    'political_affiliation_en': 'Istiqlal Party',
    'job_ar': 'محامية',
    'job_en': 'Lawyer',
    'nationality_ar': 'مغربي',
    'nationality_en': 'Moroccan',
    'second_nationality_ar': 'إسباني',
    'second_nationality_en': 'Spanish'
  }
];
